name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'infra/k8s/**'
      - '.github/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: actions-runner-controller

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # - id: auth
      #   name: 'Authenticate to Google Cloud'
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     workload_identity_provider: 'projects/1095233351226/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
      #     service_account: 'github-runner-ar@hungerstation-hackathon-6957.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Set image name
        id: vars
        run: |
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")
          IMAGE="europe-west1-docker.pkg.dev/hungerstation-hackathon-6957/build-day-25-repo/ingestion-service:${GITHUB_SHA}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: docker build -t "${{ steps.vars.outputs.image }}" .

      - name: Push image
        run: docker push "${{ steps.vars.outputs.image }}"

      - name: Update image tag
        run: |
          sed -i "s|\(image: .*ingestion-service:\).*|\1${GITHUB_SHA}|" infra/k8s/base.yaml

      - name: Commit updated manifest back to repo
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add infra/k8s/base.yaml
          git commit -m "chore: update ingestion-service image to ${GITHUB_SHA}" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/} --force
